[package]
name = "rfc-index"
version = "0.1.0"
edition = "2021"

[dependencies]
handlebars = "4.0"
mdbook = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
